from .asset_discovery_replay_cache import install_asset_discovery_replay_model_cache
from .asset_discovery_validation_policy import install_asset_discovery_validation_revision_policy

install_asset_discovery_replay_model_cache()
install_asset_discovery_validation_revision_policy()
