from .asset_discovery_replay_cache import install_asset_discovery_replay_model_cache
from .asset_discovery_replay_cache_isolation import install_asset_discovery_replay_cache_isolation
from .asset_discovery_validation_policy import install_asset_discovery_validation_revision_policy
from .asset_discovery_ranker_cache import install_asset_discovery_ranker_cache
from .asset_discovery_predictive_policy import install_asset_discovery_predictive_policy
from .asset_discovery_failure_diagnostics import install_asset_discovery_failure_diagnostics
from .asset_discovery_predictive_selection_validation import install_asset_discovery_predictive_selection_validation
from .asset_discovery_marginal_heartbeat import install_asset_discovery_marginal_heartbeat
from .asset_discovery_stop_policy import install_asset_discovery_stop_policy
from .asset_discovery_marginal_process import install_asset_discovery_marginal_process
from .asset_discovery_immediate_stop import install_asset_discovery_immediate_stop

install_asset_discovery_replay_model_cache()
install_asset_discovery_replay_cache_isolation()
install_asset_discovery_validation_revision_policy()
install_asset_discovery_ranker_cache()
install_asset_discovery_predictive_policy()
install_asset_discovery_failure_diagnostics()
install_asset_discovery_predictive_selection_validation()
install_asset_discovery_marginal_heartbeat()
install_asset_discovery_stop_policy()
install_asset_discovery_marginal_process()
install_asset_discovery_immediate_stop()
