from .asset_discovery_replay_cache import install_asset_discovery_replay_model_cache
from .asset_discovery_validation_policy import install_asset_discovery_validation_revision_policy
from .asset_discovery_ranker_cache import install_asset_discovery_ranker_cache
from .asset_discovery_predictive_policy import install_asset_discovery_predictive_policy
from .asset_discovery_failure_diagnostics import install_asset_discovery_failure_diagnostics
from .asset_discovery_predictive_history_integrity import install_asset_discovery_predictive_history_integrity
from .asset_discovery_ranked_history_retention import install_asset_discovery_ranked_history_retention
from .asset_discovery_memory_only_processing import install_asset_discovery_memory_only_processing
from .asset_discovery_marginal_replay_heartbeat import install_asset_discovery_marginal_replay_heartbeat
from .asset_discovery_predictive_selection_validation import install_asset_discovery_predictive_selection_validation

install_asset_discovery_replay_model_cache()
install_asset_discovery_validation_revision_policy()
install_asset_discovery_ranker_cache()
install_asset_discovery_predictive_policy()
install_asset_discovery_failure_diagnostics()
install_asset_discovery_predictive_history_integrity()
install_asset_discovery_ranked_history_retention()
install_asset_discovery_memory_only_processing()
install_asset_discovery_marginal_replay_heartbeat()
install_asset_discovery_predictive_selection_validation()
