from __future__ import annotations

from dataclasses import dataclass
import time
from typing import Any, Callable

import numpy as np
import pandas as pd
from sklearn.linear_model import BayesianRidge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from ..engine.capital_rotation import _model_utilities
from .counterfactual_rotation_advantage_v6 import (
    _fit_seed_model,
    _label_horizon,
    _policy_reachable_dataset,
)
from .optimal_switching_state import (
    ACTION_STATE_FEATURES,
    action_features,
    market_context,
    ranked_positions,
)


@dataclass(frozen=True)
class CounterfactualRotationAdvantageV7Settings:
    enabled: bool = False

    @classmethod
    def from_config(cls, config: Any) -> "CounterfactualRotationAdvantageV7Settings":
        research = getattr(config, "research_model_settings", {}) or {}
        raw = (
            research.get("counterfactual_rotation_advantage_v7", {})
            if isinstance(research, dict)
            else {}
        )
        if not isinstance(raw, dict):
            raw = {}
        return cls(enabled=bool(raw.get("enabled", False)))

    def as_dict(self) -> dict[str, Any]:
        return {
            "enabled": bool(self.enabled),
            "algorithm": "supervised_counterfactual_rotation_advantage_v7",
            "action_space": "HOLD incumbent reference vs ROTATE current LightGBM Top-1",
            "target": (
                "persistent relative net log-return advantage of ROTATE versus HOLD "
                "over the shortest frozen Strategy target horizon"
            ),
            "label_horizon_source": "min(rotation_target_horizons)",
            "training_state_support": (
                "single policy-reachable calibration trajectory generated by the "
                "same v4-equivalent bootstrap used in v6"
            ),
            "final_estimator": "StandardScaler + BayesianRidge",
            "estimator_rationale": (
                "sample-efficient regularized posterior regression for policy-reachable "
                "datasets where independent states can be fewer than model features"
            ),
            "decision_rule": (
                "ROTATE when posterior mean economic advantage is positive, otherwise HOLD"
            ),
            "cash_policy": "not part of this experiment; initial CASH enters current Top-1",
            "manual_switch_margin": False,
            "manual_cash_threshold": False,
            "manual_minimum_hold_guard": False,
        }


@dataclass
class FittedCounterfactualRotationAdvantageV7Model:
    model: Any
    settings: CounterfactualRotationAdvantageV7Settings
    sample_count: int
    decision_date_count: int
    seed_sample_count: int
    seed_decision_date_count: int
    calibration_start: str
    calibration_end: str
    label_horizon_sessions: int
    target_mean: float
    target_std: float
    target_positive_fraction: float
    bootstrap_rotation_fraction: float
    fit_mae: float
    fit_rmse: float
    feature_count: int
    sample_feature_ratio: float
    posterior_noise_precision: float | None
    posterior_weight_precision: float | None
    coefficient_l2_norm: float | None

    def metadata(self) -> dict[str, Any]:
        return {
            **self.settings.as_dict(),
            "sample_count": int(self.sample_count),
            "decision_date_count": int(self.decision_date_count),
            "seed_sample_count": int(self.seed_sample_count),
            "seed_decision_date_count": int(self.seed_decision_date_count),
            "calibration_start": self.calibration_start,
            "calibration_end": self.calibration_end,
            "label_horizon_sessions": int(self.label_horizon_sessions),
            "target_mean": float(self.target_mean),
            "target_std": float(self.target_std),
            "target_positive_fraction": float(self.target_positive_fraction),
            "bootstrap_rotation_fraction": float(self.bootstrap_rotation_fraction),
            "fit_mae": float(self.fit_mae),
            "fit_rmse": float(self.fit_rmse),
            "feature_count": int(self.feature_count),
            "sample_feature_ratio": float(self.sample_feature_ratio),
            "posterior_noise_precision": self.posterior_noise_precision,
            "posterior_weight_precision": self.posterior_weight_precision,
            "coefficient_l2_norm": self.coefficient_l2_norm,
        }


def _posterior_regressor() -> Pipeline:
    return Pipeline(
        steps=[
            ("scale", StandardScaler()),
            ("regressor", BayesianRidge(compute_score=True)),
        ]
    )


def fit_counterfactual_rotation_advantage_v7(
    *,
    utility_models: dict[str, Any],
    frames: dict[str, pd.DataFrame],
    symbols: list[str],
    calibration_dates: pd.DatetimeIndex,
    config: Any,
    model_settings: dict[str, Any],
    technical_log_callback: Callable[[str], None] | None = None,
) -> FittedCounterfactualRotationAdvantageV7Model:
    settings = CounterfactualRotationAdvantageV7Settings.from_config(config)
    if not settings.enabled:
        raise ValueError(
            "Counterfactual Rotation Advantage v7 research is not enabled."
        )

    dates = pd.DatetimeIndex(calibration_dates).sort_values()
    horizon_sessions = _label_horizon(config)
    usable_decision_count = len(dates) - horizon_sessions
    if usable_decision_count < 10:
        raise ValueError(
            "Counterfactual Rotation Advantage v7 needs at least ten calibration "
            "decisions after purging its persistence label horizon."
        )

    started = time.perf_counter()
    if technical_log_callback is not None:
        technical_log_callback(
            "model=counterfactual_rotation_advantage_v7 event=seed_fit_start "
            f"sessions={len(dates)} usable_sessions={usable_decision_count} "
            f"label_horizon_sessions={horizon_sessions}"
        )

    seed_model, seed_sample_count, seed_decision_date_count = _fit_seed_model(
        utility_models=utility_models,
        frames=frames,
        symbols=symbols,
        dates=dates,
        horizon_sessions=horizon_sessions,
        config=config,
        model_settings=model_settings,
    )
    x, y, w, decision_date_count, bootstrap_rotation_fraction = (
        _policy_reachable_dataset(
            seed_model=seed_model,
            utility_models=utility_models,
            frames=frames,
            symbols=symbols,
            dates=dates,
            horizon_sessions=horizon_sessions,
            config=config,
        )
    )

    if len(x) != len(y):
        raise RuntimeError("CRA v7 policy-reachable feature/target lengths diverged.")
    if len(x) < 2:
        raise RuntimeError("CRA v7 requires at least two policy-reachable samples.")

    model = _posterior_regressor()
    model.fit(x, y)
    predicted = np.asarray(model.predict(x), dtype=float)
    residual = predicted - y

    normalized_weights = np.asarray(w, dtype=float)
    if len(normalized_weights) != len(y) or float(normalized_weights.sum()) <= 0.0:
        normalized_weights = np.ones(len(y), dtype=float)

    fit_mae = float(np.average(np.abs(residual), weights=normalized_weights))
    fit_rmse = float(
        np.sqrt(np.average(np.square(residual), weights=normalized_weights))
    )
    target_mean = float(np.average(y, weights=normalized_weights))
    target_std = float(
        np.sqrt(
            np.average(
                np.square(y - target_mean),
                weights=normalized_weights,
            )
        )
    )
    target_positive_fraction = float(
        np.average((y > 0.0).astype(float), weights=normalized_weights)
    )

    posterior = model.named_steps["regressor"]
    posterior_noise_precision = (
        float(posterior.alpha_)
        if getattr(posterior, "alpha_", None) is not None
        and np.isfinite(float(posterior.alpha_))
        else None
    )
    posterior_weight_precision = (
        float(posterior.lambda_)
        if getattr(posterior, "lambda_", None) is not None
        and np.isfinite(float(posterior.lambda_))
        else None
    )
    coef = np.asarray(getattr(posterior, "coef_", []), dtype=float)
    coefficient_l2_norm = (
        float(np.linalg.norm(coef)) if coef.size and np.all(np.isfinite(coef)) else None
    )
    feature_count = int(len(ACTION_STATE_FEATURES))
    sample_feature_ratio = float(len(x) / max(1, feature_count))

    if technical_log_callback is not None:
        technical_log_callback(
            "model=counterfactual_rotation_advantage_v7 event=fit_complete "
            f"seed_samples={seed_sample_count} "
            f"seed_decision_dates={seed_decision_date_count} "
            f"policy_reachable_samples={len(x)} "
            f"policy_reachable_decision_dates={decision_date_count} "
            f"feature_count={feature_count} "
            f"sample_feature_ratio={sample_feature_ratio:.4f} "
            f"bootstrap_rotation_fraction={bootstrap_rotation_fraction:.4f} "
            f"target_mean={target_mean:.8f} "
            f"positive_fraction={target_positive_fraction:.4f} "
            f"fit_mae={fit_mae:.8f} fit_rmse={fit_rmse:.8f} "
            f"duration_seconds={time.perf_counter() - started:.3f}"
        )

    return FittedCounterfactualRotationAdvantageV7Model(
        model=model,
        settings=settings,
        sample_count=int(len(x)),
        decision_date_count=int(decision_date_count),
        seed_sample_count=int(seed_sample_count),
        seed_decision_date_count=int(seed_decision_date_count),
        calibration_start=pd.Timestamp(dates[0]).date().isoformat(),
        calibration_end=pd.Timestamp(dates[usable_decision_count - 1]).date().isoformat(),
        label_horizon_sessions=int(horizon_sessions),
        target_mean=target_mean,
        target_std=target_std,
        target_positive_fraction=target_positive_fraction,
        bootstrap_rotation_fraction=float(bootstrap_rotation_fraction),
        fit_mae=fit_mae,
        fit_rmse=fit_rmse,
        feature_count=feature_count,
        sample_feature_ratio=sample_feature_ratio,
        posterior_noise_precision=posterior_noise_precision,
        posterior_weight_precision=posterior_weight_precision,
        coefficient_l2_norm=coefficient_l2_norm,
    )


def build_counterfactual_rotation_advantage_v7_policy(
    *,
    fitted_model: FittedCounterfactualRotationAdvantageV7Model,
    utility_models: dict[str, Any],
    frames: dict[str, pd.DataFrame],
    symbols: list[str],
    config: Any,
    diagnostics: dict[pd.Timestamp, dict[str, Any]],
    fold_id: int,
) -> Callable[[pd.Timestamp, int, int], tuple[int, float]]:
    def policy(
        timestamp: pd.Timestamp,
        current_position: int,
        holding_days: int,
    ) -> tuple[int, float]:
        del holding_days
        key = pd.Timestamp(timestamp)
        utilities = _model_utilities(utility_models, frames, symbols, key, config)
        ranked = ranked_positions(utilities)
        context = market_context(frames, symbols, key, utilities)
        best = int(ranked[0]) if ranked else 0

        best_score = (
            float(utilities[best])
            if best > 0 and np.isfinite(utilities[best])
            else 0.0
        )
        current_score = (
            float(utilities[current_position])
            if current_position > 0 and np.isfinite(utilities[current_position])
            else 0.0
        )

        rotation_advantage: float | None = None
        if current_position <= 0:
            selected = best
            reason = "CRA7_ENTER_TOP1"
        elif best <= 0 or best == current_position:
            selected = current_position
            reason = "CRA7_HOLD_CURRENT_TOP1"
            rotation_advantage = 0.0
        else:
            matrix = pd.DataFrame(
                [
                    action_features(
                        frames=frames,
                        symbols=symbols,
                        timestamp=key,
                        utilities=utilities,
                        context=context,
                        current_position=current_position,
                        target_position=best,
                        config=config,
                    )
                ],
                columns=list(ACTION_STATE_FEATURES),
            ).fillna(0.0)
            predicted = float(fitted_model.model.predict(matrix)[0])
            rotation_advantage = predicted if np.isfinite(predicted) else None
            if rotation_advantage is not None and rotation_advantage > 0.0:
                selected = best
                reason = "CRA7_ROTATE_POSITIVE_POSTERIOR_ADVANTAGE"
            else:
                selected = current_position
                reason = "CRA7_HOLD_NONPOSITIVE_POSTERIOR_ADVANTAGE"

        selected_score = (
            float(utilities[selected])
            if selected > 0 and np.isfinite(utilities[selected])
            else 0.0
        )
        diagnostics[key] = {
            "decision_diagnostics_schema_version": 36,
            "decision_fold_id": int(fold_id),
            "decision_reason": reason,
            "counterfactual_rotation_advantage_v7_enabled": True,
            "current_asset": (
                symbols[current_position - 1] if current_position > 0 else "CASH"
            ),
            "current_score": current_score,
            "current_asset_rank": (
                context["ranks"].get(current_position)
                if current_position > 0
                else None
            ),
            "best_asset": symbols[best - 1] if best > 0 else "CASH",
            "best_score": best_score,
            "best_vs_current_gap": best_score - current_score,
            "universe_score_mean": float(context["mean"]),
            "universe_score_std": float(context["std"]),
            "final_action_asset": (
                symbols[selected - 1] if selected > 0 else "CASH"
            ),
            "final_action_score": selected_score,
            "decision_is_rotation": bool(
                current_position > 0
                and selected > 0
                and selected != current_position
            ),
            "cra7_reference_asset": (
                symbols[current_position - 1] if current_position > 0 else "CASH"
            ),
            "cra7_reference_advantage": 0.0,
            "cra7_rotation_candidate_asset": (
                symbols[best - 1] if best > 0 else None
            ),
            "cra7_rotation_advantage": rotation_advantage,
            "cra7_positive_advantage": bool(
                rotation_advantage is not None and rotation_advantage > 0.0
            ),
            "cra7_label_horizon_sessions": int(
                fitted_model.label_horizon_sessions
            ),
            "cra7_training_state_support": "policy_reachable",
            "cra7_final_estimator": "bayesian_ridge",
            "cra7_training_decision_dates": int(
                fitted_model.decision_date_count
            ),
            "cra7_seed_decision_dates": int(
                fitted_model.seed_decision_date_count
            ),
            "cra7_sample_feature_ratio": float(
                fitted_model.sample_feature_ratio
            ),
            "cra7_cash_action_enabled": False,
        }
        for index, position in enumerate(ranked[:3], start=1):
            diagnostics[key][f"top_{index}_asset"] = symbols[position - 1]
            diagnostics[key][f"top_{index}_score"] = float(utilities[position])
        return selected, selected_score

    return policy
