"""v10.8.48 policy-rollout capital advantage meta-veto.

The v10.8.44 Liquidity-Aware Control remains the default policy.  The only new
question is whether one Control-proposed asset-to-asset rotation should be
vetoed once.  Labels are generated by two execution-aware rollouts from the
same audited historical portfolio state:

    DeltaCapital = ending_equity(ROTATE now, then Control)
                 - ending_equity(HOLD once, then Control)

Both branches reuse the same Control/Liquidity-Aware policy, the same 10%
capacity/cost execution model and a fixed 20-session horizon.

Causal protocol:
- fold 1: meta-model disabled;
- fold 2: may learn only from fully matured fold-1 OOS opportunities;
- fold 3: may learn only from fully matured fold-1/2 OOS opportunities;
- historical eligible labels are split chronologically 70/30 for train vs
  calibration;
- the fail-safe calibration gate from v10.8.47 remains unchanged.

No live strategy registration and no order path.
"""
from __future__ import annotations

from dataclasses import dataclass
from types import FunctionType
from typing import Any, Callable
import math

import numpy as np
import pandas as pd

from ..tcc_v106_reference import research_challengers as scientific
from ..tcc_v106_reference.capital_rotation import _utility_policy as frozen_utility_policy
from .control_execution_feasibility import simulate_feasible_control
from .control_liquidity_policy import _CapitalAwareUtilityCache
from .control_counterfactual_advantage import (
    PairSample,
    RANDOM_SEED,
    MIN_CALIBRATION_SAMPLES,
    apply_meta_veto,
    fit_meta_veto,
    predict_rotation_advantage_probability,
    refit_meta_veto,
)

MODE = "MCT_RESEARCH_CONTROL_POLICY_ROLLOUT_ADVANTAGE_V1"
ROLLOUT_HORIZON_SESSIONS = 20
TRAIN_FRACTION = 0.70
MIN_TRAIN_SAMPLES = 40


@dataclass(frozen=True)
class HistoricalState:
    decision_date: pd.Timestamp
    cash: float
    position: int
    shares: int
    holding_days: int
    equity: float

    def as_initial_state(self) -> dict[str, Any]:
        return {
            "cash": self.cash,
            "position": self.position,
            "shares": self.shares,
            "holding_days": self.holding_days,
            "equity": self.equity,
        }


def _position(symbols: list[str], asset: str) -> int:
    normalized = str(asset).upper()
    if normalized == "CASH":
        return 0
    try:
        return symbols.index(normalized) + 1
    except ValueError as exc:
        raise ValueError(f"Unknown rollout asset {normalized}.") from exc


def _pair_sample(
    frames: dict[str, pd.DataFrame],
    row: dict[str, Any],
) -> PairSample:
    date = pd.Timestamp(row["decision_date"])
    incumbent = str(row["incumbent_asset"])
    candidate = str(row["control_target_asset"])
    iloc = int(frames[incumbent].index.get_indexer([date])[0])
    cloc = int(frames[candidate].index.get_indexer([date])[0])
    if min(iloc, cloc) < 39:
        raise ValueError("Rollout sample lacks the fixed 40-session feature window.")
    return PairSample(
        decision_date=date,
        incumbent=incumbent,
        candidate=candidate,
        incumbent_loc=iloc,
        candidate_loc=cloc,
        advantage=float(row["delta_capital_usd"]),
    )


def _paired_rollout(
    *,
    decision_date: pd.Timestamp,
    incumbent_asset: str,
    candidate_asset: str,
    state: HistoricalState,
    policy: Callable[[pd.Timestamp, int, int], tuple[int, float]],
    frames: dict[str, pd.DataFrame],
    symbols: list[str],
    decision_dates: pd.DatetimeIndex,
    config: Any,
    fee_calculator: Callable,
    slippage: Callable,
    decision_metadata: dict[pd.Timestamp, dict[str, Any]] | None,
    prepare_account: Callable[[pd.Timestamp, int, int, float, int, float], None],
) -> dict[str, Any] | None:
    """Two branches from the exact same state; only the first action differs."""
    key = pd.Timestamp(decision_date)
    positions = decision_dates.get_indexer([key])
    if len(positions) != 1 or int(positions[0]) < 0:
        raise ValueError("Rollout decision date missing from OOS calendar.")
    start = int(positions[0])
    stop = start + ROLLOUT_HORIZON_SESSIONS
    if stop >= len(decision_dates):
        return None
    segment = pd.DatetimeIndex(decision_dates[start:stop + 1])
    current_position = int(state.position)
    candidate_position = _position(symbols, candidate_asset)
    if current_position <= 0 or candidate_position <= 0 or candidate_position == current_position:
        return None

    def branch(first_target: int, label: str):
        first = [True]

        def branch_policy(
            timestamp: pd.Timestamp,
            actual_position: int,
            holding_days: int,
        ) -> tuple[int, float]:
            if first[0]:
                first[0] = False
                if pd.Timestamp(timestamp) != key:
                    raise ValueError("Paired rollout first decision date changed.")
                return int(first_target), 0.0
            return policy(timestamp, actual_position, holding_days)

        return simulate_feasible_control(
            f"policy_rollout_{label}",
            branch_policy,
            frames,
            symbols,
            segment,
            config,
            fee_calculator,
            slippage,
            decision_metadata=decision_metadata,
            scenario_override=None,
            decision_prepare=prepare_account,
            initial_state=state.as_initial_state(),
        )

    rotate = branch(candidate_position, "rotate")
    hold = branch(current_position, "hold")
    rotate_end = float(rotate.metrics["strategy_ending_capital"])
    hold_end = float(hold.metrics["strategy_ending_capital"])
    if not (math.isfinite(rotate_end) and math.isfinite(hold_end)):
        raise ValueError("Non-finite paired rollout ending equity.")
    return {
        "decision_date": key,
        "rollout_end_date": pd.Timestamp(segment[-1]),
        "incumbent_asset": incumbent_asset,
        "control_target_asset": candidate_asset,
        "source_fold_id": int(
            (decision_metadata or {}).get(key, {}).get("fold_id") or 0
        ),
        "initial_equity": float(state.equity),
        "rotate_ending_equity": rotate_end,
        "hold_ending_equity": hold_end,
        "delta_capital_usd": rotate_end - hold_end,
        "delta_capital_fraction": (
            (rotate_end - hold_end) / float(state.equity)
            if state.equity else None
        ),
        "rotate_better": rotate_end > hold_end,
        "rollout_horizon_sessions": ROLLOUT_HORIZON_SESSIONS,
    }


def _chronological_split(
    samples: list[PairSample],
) -> tuple[list[PairSample], list[PairSample]]:
    ordered = sorted(samples, key=lambda x: x.decision_date)
    if len(ordered) < MIN_TRAIN_SAMPLES + MIN_CALIBRATION_SAMPLES:
        return [], []
    cut = int(math.floor(len(ordered) * TRAIN_FRACTION))
    cut = max(MIN_TRAIN_SAMPLES, cut)
    cut = min(cut, len(ordered) - MIN_CALIBRATION_SAMPLES)
    if cut <= 0 or cut >= len(ordered):
        return [], []
    return ordered[:cut], ordered[cut:]


def _train_meta_by_fold(
    *,
    frames: dict[str, pd.DataFrame],
    folds: list[dict[str, Any]],
    rollout_rows: list[dict[str, Any]],
) -> tuple[dict[int, dict[str, Any]], list[dict[str, Any]]]:
    meta: dict[int, dict[str, Any]] = {}
    reports: list[dict[str, Any]] = []
    for fold in folds:
        fid = int(fold["fold_id"])
        test_start = pd.Timestamp(fold["test_start"])
        eligible_rows = [
            row for row in rollout_rows
            if int(row["source_fold_id"]) < fid
            and pd.Timestamp(row["rollout_end_date"]) < test_start
        ]
        samples = [_pair_sample(frames, row) for row in eligible_rows]
        training, calibration = _chronological_split(samples)

        if fid == 1 or not training or not calibration:
            meta[fid] = {
                "enabled": False, "model": None, "scale": None,
            }
            reports.append({
                "fold_id": fid,
                "eligible_prior_rollouts": len(samples),
                "training_samples": len(training),
                "calibration_samples": len(calibration),
                "model_enabled": False,
                "disable_reason": (
                    "NO_PRIOR_OOS_FOLD" if fid == 1
                    else "INSUFFICIENT_PRIOR_ROLLOUT_SAMPLES"
                ),
                "test_start": test_start.isoformat(),
                "test_end": pd.Timestamp(fold["test_end"]).isoformat(),
            })
            continue

        _cal_model, _cal_scale, epochs, validation = fit_meta_veto(
            frames,
            training,
            calibration,
            seed=RANDOM_SEED + 1000 + fid,
        )
        all_prior = training + calibration
        if bool(validation["model_enabled"]):
            model, scale = refit_meta_veto(
                frames,
                all_prior,
                seed=RANDOM_SEED + 2000 + fid,
                epochs=epochs,
            )
        else:
            model, scale = None, None
        meta[fid] = {
            "enabled": bool(validation["model_enabled"]),
            "model": model,
            "scale": scale,
        }
        reports.append({
            "fold_id": fid,
            "eligible_prior_rollouts": len(samples),
            "training_samples": len(training),
            "calibration_samples": len(calibration),
            "final_training_samples": len(all_prior),
            "label_positive_rate": float(
                np.mean([sample.label for sample in all_prior])
            ),
            "test_start": test_start.isoformat(),
            "test_end": pd.Timestamp(fold["test_end"]).isoformat(),
            **validation,
        })
    return meta, reports


def run_policy_rollout_meta_veto_pair(
    bars: dict[str, pd.DataFrame],
    config: Any,
    fee_calculator: Callable,
    slippage: Callable,
    *,
    progress_callback: Callable[[float, str, int], None] | None = None,
) -> tuple[
    dict[str, Any],
    list[dict[str, Any]],
    list[dict[str, Any]],
    list[dict[str, Any]],
]:
    """One Control fit, exact v10.8.44 baseline, causal rollout labels, meta replay."""
    (
        frames, _common_dates, symbols, folds, all_decision_dates,
        _decision_to_fold, decision_metadata,
    ) = scientific._build_execution_context(bars, config)
    if len(symbols) != 55 or len(folds) != 3:
        raise ValueError("v10.8.48 expects frozen 55-asset / 3-fold Control context.")

    original_runner = scientific._run_lightgbm
    original_policy = original_runner.__globals__.get("_utility_policy")
    original_simulator = original_runner.__globals__.get("_simulate_exact")
    if original_policy is not frozen_utility_policy or original_simulator is not scientific._simulate_exact:
        raise RuntimeError("Frozen Control runner bindings changed unexpectedly.")

    account: dict[str, Any] = {"enabled": True, "audit": {}}
    baseline_states: dict[pd.Timestamp, HistoricalState] = {}

    def prepare_account(date, position, holding, cash, shares, equity):
        account.update({
            "decision_timestamp": pd.Timestamp(date),
            "position": int(position),
            "holding_days": int(holding),
            "cash": float(cash),
            "shares": int(shares),
            "equity": float(equity),
        })

    def policy_wrapper(models, panel, labels, settings, switch_margin, **kwargs):
        utility_cache = kwargs.get("utility_cache")
        if utility_cache is None:
            return original_policy(
                models, panel, labels, settings, switch_margin, **kwargs,
            )
        liquidity_cache = _CapitalAwareUtilityCache(
            utility_cache, panel, labels, account,
        )
        base_kwargs = dict(kwargs)
        base_kwargs["utility_cache"] = liquidity_cache
        return original_policy(
            models, panel, labels, settings, switch_margin, **base_kwargs,
        )

    captured: dict[str, Any] = {}
    rollout_rows: list[dict[str, Any]] = []
    training_reports: list[dict[str, Any]] = []
    meta_audit: list[dict[str, Any]] = []

    def simulator_wrapper(*args, **kwargs):
        if captured:
            raise ValueError("v10.8.48 expected exactly one scheduled OOS simulator call.")

        backend, scheduled, panel, labels, dates, settings, fees, slip = args[:8]
        metadata = kwargs.get("decision_metadata") or decision_metadata

        def capture_state(date, position, holding, cash, shares, equity):
            prepare_account(date, position, holding, cash, shares, equity)
            baseline_states[pd.Timestamp(date)] = HistoricalState(
                decision_date=pd.Timestamp(date),
                cash=float(cash),
                position=int(position),
                shares=int(shares),
                holding_days=int(holding),
                equity=float(equity),
            )

        baseline = simulate_feasible_control(
            backend, scheduled, panel, labels, dates, settings, fees, slip,
            **{
                **kwargs,
                "decision_prepare": capture_state,
            },
        )
        captured["liquidity_baseline"] = baseline

        if len(baseline_states) != len(baseline.predictions):
            raise ValueError("Baseline historical-state capture is incomplete.")

        if progress_callback:
            progress_callback(93.0, "Building paired policy-rollout labels", 0)

        candidates = baseline.predictions.loc[
            (baseline.predictions["previous_asset"] != "CASH")
            & (baseline.predictions["signal_asset"] != "CASH")
            & (
                baseline.predictions["previous_asset"]
                != baseline.predictions["signal_asset"]
            )
        ]
        for ordinal, (_, row) in enumerate(candidates.iterrows(), start=1):
            decision_date = pd.Timestamp(row["decision_date"])
            state = baseline_states.get(decision_date)
            if state is None:
                raise ValueError("Missing audited state for rollout opportunity.")
            result = _paired_rollout(
                decision_date=decision_date,
                incumbent_asset=str(row["previous_asset"]),
                candidate_asset=str(row["signal_asset"]),
                state=state,
                policy=scheduled,
                frames=panel,
                symbols=labels,
                decision_dates=pd.DatetimeIndex(dates),
                config=settings,
                fee_calculator=fees,
                slippage=slip,
                decision_metadata=metadata,
                prepare_account=prepare_account,
            )
            if result is not None:
                rollout_rows.append(result)
            if progress_callback and (
                ordinal % max(1, len(candidates)//10) == 0
                or ordinal == len(candidates)
            ):
                progress_callback(
                    93.0 + 3.0 * ordinal / max(1, len(candidates)),
                    f"Paired rollouts {ordinal}/{len(candidates)}",
                    ordinal,
                )

        meta_by_fold, reports = _train_meta_by_fold(
            frames=panel,
            folds=folds,
            rollout_rows=rollout_rows,
        )
        training_reports.extend(reports)

        def meta_policy(
            timestamp: pd.Timestamp,
            current_position: int,
            holding_days: int,
        ) -> tuple[int, float]:
            control_target, control_score = scheduled(
                timestamp, current_position, holding_days,
            )
            fid = int(
                (metadata or {}).get(pd.Timestamp(timestamp), {}).get("fold_id") or 0
            )
            state = meta_by_fold.get(fid) or {
                "enabled": False, "model": None, "scale": None,
            }
            current_asset = (
                labels[current_position-1] if current_position > 0 else "CASH"
            )
            candidate_asset = (
                labels[control_target-1] if control_target > 0 else "CASH"
            )
            probability = None
            if (
                bool(state["enabled"])
                and current_position > 0
                and control_target > 0
                and current_position != control_target
            ):
                probability = predict_rotation_advantage_probability(
                    state["model"],
                    state["scale"],
                    panel,
                    date=pd.Timestamp(timestamp),
                    incumbent=current_asset,
                    candidate=candidate_asset,
                )
            final_target, reason = apply_meta_veto(
                current_position=int(current_position),
                control_target=int(control_target),
                probability_positive_advantage=probability,
                model_enabled=bool(state["enabled"]),
            )
            meta_audit.append({
                "decision_date": pd.Timestamp(timestamp),
                "fold_id": fid,
                "incumbent_asset": current_asset,
                "control_target_asset": candidate_asset,
                "final_target_asset": (
                    labels[final_target-1] if final_target > 0 else "CASH"
                ),
                "probability_positive_rollout_advantage": probability,
                "model_enabled": bool(state["enabled"]),
                "veto_applied": int(final_target) != int(control_target),
                "reason": reason,
            })
            return int(final_target), float(control_score)

        captured["meta_veto"] = simulate_feasible_control(
            backend,
            meta_policy,
            panel,
            labels,
            dates,
            settings,
            fees,
            slip,
            **{
                **kwargs,
                "decision_prepare": prepare_account,
            },
        )
        return baseline

    isolated_globals = dict(original_runner.__globals__)
    isolated_globals["_utility_policy"] = policy_wrapper
    isolated_globals["_simulate_exact"] = simulator_wrapper
    isolated = FunctionType(
        original_runner.__code__, isolated_globals, original_runner.__name__,
        original_runner.__defaults__, original_runner.__closure__,
    )
    isolated.__kwdefaults__ = dict(original_runner.__kwdefaults__ or {})
    result = isolated(
        bars, config, fee_calculator, slippage,
        progress_callback=progress_callback,
        trade_callback=None,
        progress_detail_callback=None,
        technical_log_callback=None,
    )
    if (
        len(result) != 1
        or result[0] is not captured.get("liquidity_baseline")
        or set(captured) != {"liquidity_baseline", "meta_veto"}
    ):
        raise ValueError("v10.8.48 paired replay did not produce baseline and meta paths.")
    if (
        original_runner.__globals__.get("_utility_policy") is not original_policy
        or original_runner.__globals__.get("_simulate_exact") is not original_simulator
    ):
        raise RuntimeError("Frozen TCC module was mutated by v10.8.48.")

    return captured, rollout_rows, training_reports, meta_audit
