export const ACTIVE_JOB_STATUSES = new Set(['queued', 'running'])

export const STATUS_LABELS = {
  saved: 'Saved',
  research: 'Research',
  draft: 'Draft',
  backtest: 'Backtest',
  candidate: 'Candidate',
  superseded_candidate: 'Superseded candidate',
  promoted_candidate: 'Promoted candidate',
  winner: 'Winner',
  former_winner: 'Former winner',
}

export const STRATEGY_FIELD_HINTS = {
  name: {
    description: 'Sequential visual identity generated by the backend as Strategy #N.',
    relationship: 'The name is presentation-only. IDs and immutable snapshots drive selection, lineage and execution.',
  },
  description: {
    description: 'Exact Git commit subject associated with the code that created this Strategy.',
    relationship: 'The description is generated by the backend and is not editable in the Catalog.',
  },
  search: {
    description: 'Filters the editable configuration by visible label, technical parameter name, group name or available schema metadata.',
    relationship: 'Filtering changes only what is visible in this page; it never changes the strategy configuration.',
  },
  changeReason: {
    description: 'Optional audit note explaining why this strategy revision is being changed.',
    relationship: 'Saving an editable draft revision does not require a note; provide one only when it adds useful research context.',
  },
}

export const BOUNDARY_HINTS = {
  winner: {
    description: 'The single Strategy currently holding the WINNER role.',
    relationship: 'Promotion changes only the Catalog role. The Strategy ID, sequential name and lineage remain unchanged.',
  },
  backtest: {
    description: 'The single Strategy currently holding the RESEARCH role.',
    relationship: 'Marking another Strategy as RESEARCH automatically removes the role from the previous Research Strategy.',
  },
  lifecycle: {
    description: 'The Catalog allows at most one RESEARCH role and one WINNER role.',
    relationship: 'Every other Strategy remains SAVED. The newest saved Strategy is shown immediately below the Winner.',
  },
}
